1. SELECT COUNT(orders.id) AS total_order, COUNT(product.product_name) as total_item, SUM(order_detail.qty) as total_qty, SUM(orders.delivery_fee) as total_ongkir, SUM(orders.payment_discount) as total_diskon, SUM(orders.payment_final) as total_pembayaran FROM order_detail JOIN product ON product.id=order_detail.product_id JOIN orders ON orders.id=order_detail.order_id WHERE order_time;
2. SELECT name, COUNT(*) AS Orderan FROM `orders` GROUP BY name;
3. SELECT name, COUNT(*) AS Orderan_keAgent FROM `orders` GROUP BY agent_name;
4. SELECT order_detail.product_id, product.product_name,(order_detail.price) AS HargaJual, (order_detail.price_agent) AS HargaBeliAgent,(order_detail.qty) AS QTY, ((order_detail.price)*qty) AS TotalHargaJual, ((order_detail.price_agent)*qty) AS TotalHargaBeliAgent ,((order_detail.price)*qty) - ((order_detail.price_agent)*qty) as KeuntunganAgent FROM `order_detail` INNER JOIN product ON order_detail.product_id = product.id GROUP BY order_detail.product_id;
5. SELECT product.id, product.product_name, (order_detail.price) AS HargaJual, (order_detail.qty) AS QTY, ((order_detail.price)*order_detail.qty) AS TotalHargaJual FROM `order_detail` INNER JOIN product ON order_detail.product_id = product.id GROUP BY product.id;
6. SELECT product_category.name, order_detail.qty, order_detail.total_price FROM `order_detail` INNER JOIN product ON order_detail.product_id = product.id INNER JOIN product_category ON product.category = product_category.id GROUP BY product_category.name;
7. SELECT order_detail.product_id,product.product_name, COUNT(order_detail.product_id) as total_terjual FROM order_detail INNER JOIN product ON order_detail.product_id = product.id GROUP BY order_detail.product_id ORDER BY total_terjual DESC LIMIT 10;
8. SELECT orders.customer_id,orders.name, COUNT(orders.customer_id) as total_pembelian FROM orders INNER JOIN customer ON orders.customer_id = customer.id GROUP BY orders.customer_id ORDER BY `total_pembelian` DESC LIMIT 10;
9. SELECT agent_name, COUNT(*) as Customer FROM `orders`GROUP BY agent_name ORDER BY Customer DESC LIMIT 10;
